managerServer:
  hostname: "127.0.0.1"
  port: 1337
dataServer:
  hostname: "127.0.0.1"
  port: 1338
servers:
  - managerServer:
      hostname: "127.0.0.1"
      port: 1337
    dataServer:
      hostname: "127.0.0.1"
      port: 1338